- repo: ntpeters/vim-better-whitespace
- repo: shime/vim-livedown
- repo: kassio/neoterm
- repo: szw/vim-maximizer
- repo: xolox/vim-notes
- repo: xolox/vim-misc
- repo: dhruvasagar/vim-zoom
- repo: tpope/vim-rbenv
- repo: equalsraf/neovim-gui-shim
- repo: rafi/vim-venom
  on_ft: python
